<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Calculator.Events.Handlers.Composites\Calculator.Events.Handlers.Composites.csproj" />
      <ProjectReference Include="..\Calculator.States.Contexts\Calculator.States.Contexts.csproj" />
      <ProjectReference Include="..\Calculator.States.Handlers\Calculator.States.Handlers.csproj" />
      <ProjectReference Include="..\Calculator.States.Interfaces\Calculator.States.Interfaces.csproj" />
      <ProjectReference Include="..\DependencyInjection.Strategies.Interfaces\DependencyInjection.Strategies.Interfaces.csproj" />
    </ItemGroup>

</Project>
