<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Calculator.Utils\Calculator.Utils.csproj" />
      <ProjectReference Include="..\DependencyInjection.Interfaces\DependencyInjection.Interfaces.csproj" />
      <ProjectReference Include="..\DependencyInjection.Strategies.Interfaces\DependencyInjection.Strategies.Interfaces.csproj" />
    </ItemGroup>

</Project>
