<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Calculator.Commands.Handlers.Interfaces\Calculator.Commands.Handlers.Interfaces.csproj" />
      <ProjectReference Include="..\Calculator.Commands\Calculator.Commands.csproj" />
      <ProjectReference Include="..\Calculator.Events.Handlers.Interfaces\Calculator.Events.Handlers.Interfaces.csproj" />
      <ProjectReference Include="..\Calculator.Events\Calculator.Events.csproj" />
      <ProjectReference Include="..\Calculator.Queries.Handlers.Interfaces\Calculator.Queries.Handlers.Interfaces.csproj" />
      <ProjectReference Include="..\Calculator.Queries\Calculator.Queries.csproj" />
      <ProjectReference Include="..\Calculator.States.Interfaces\Calculator.States.Interfaces.csproj" />
      <ProjectReference Include="..\DependencyInjection.Strategies.Interfaces\DependencyInjection.Strategies.Interfaces.csproj" />
    </ItemGroup>

</Project>
