<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Calculator.Services.Contexts\Calculator.Services.Contexts.csproj" />
      <ProjectReference Include="..\Calculator.Services.Inputs\Calculator.Services.Inputs.csproj" />
      <ProjectReference Include="..\Calculator.Services.Results\Calculator.Services.Results.csproj" />
      <ProjectReference Include="..\Calculator.Services.Interfaces\Calculator.Services.Interfaces.csproj" />
      <ProjectReference Include="..\Calculator.States.Contexts.Interfaces\Calculator.States.Contexts.Interfaces.csproj" />
      <ProjectReference Include="..\DependencyInjection.Strategies.Interfaces\DependencyInjection.Strategies.Interfaces.csproj" />
    </ItemGroup>

</Project>
