<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Calculator.Queries.Handlers.Interfaces\Calculator.Queries.Handlers.Interfaces.csproj" />
      <ProjectReference Include="..\Calculator.Queries.Handlers\Calculator.Queries.Handlers.csproj" />
      <ProjectReference Include="..\Calculator.Queries\Calculator.Queries.csproj" />
      <ProjectReference Include="..\DependencyInjection.Interfaces\DependencyInjection.Interfaces.csproj" />
    </ItemGroup>

</Project>
